# Generated by Django 2.1.7 on 2019-04-23 19:21

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusService',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('route', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=api.models.BusService.default_array_field, size=None)),
                ('timing', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=api.models.BusService.default_array_field, size=None)),
                ('boarding_point', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=api.models.BusService.default_array_field, size=None)),
                ('price', models.IntegerField(default=0)),
                ('bus_number', models.CharField(blank=True, default='', max_length=20)),
                ('is_ready', models.BooleanField(default=False)),
                ('provider', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=api.models.BusService.default_array_field, size=None)),
                ('seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('in_date', models.DateField()),
                ('out_date', models.DateField()),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('rooms', models.IntegerField(default=0)),
                ('bill', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('provider', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=api.models.HotelService.default_array_field, size=None)),
                ('rooms', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('token', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('U', 'Standard User'), ('A', 'Admin'), ('S', 'Service Provider')], max_length=1)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
