# Generated by Django 2.1.7 on 2019-04-09 20:16

import database.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDetails',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ip_addr', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=8)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMetaData',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('B', 'Bus'), ('H', 'Hotel')], max_length=1)),
                ('db_name', models.CharField(max_length=50)),
                ('provider', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=database.models.ServiceMetaData.default_array_field, size=None)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserMetaData',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=50)),
            ],
        ),
    ]
