# Generated by Django 2.1.7 on 2019-04-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemetadata',
            name='capacity',
        ),
    ]
