# Generated by Django 2.1.7 on 2019-04-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_servicemetadata_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemetadata',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
