# Generated by Django 2.1.7 on 2019-03-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_usermetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDetails',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ip_addr', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=8)),
            ],
        ),
    ]
