# Generated by Django 2.1.7 on 2019-04-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_servicemetadata_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMetaData',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('B', 'Bus'), ('H', 'Hotel')], max_length=1)),
                ('db_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
