# Generated by Django 2.1.7 on 2019-03-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_databasedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseSize',
        ),
        migrations.AddField(
            model_name='databasedetails',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
