# Generated by Django 2.1.7 on 2019-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_bookingmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasedetails',
            name='status',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
