# Generated by Django 2.1.7 on 2019-03-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190310_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMetaData',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('B', 'Bus'), ('H', 'Hotel')], max_length=1)),
                ('db_name', models.CharField(max_length=50)),
            ],
        ),
    ]
