# Generated by Django 2.1.7 on 2019-04-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_databasedetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='db_name_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='db_name_2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
