# Generated by Django 2.1.7 on 2019-03-18 14:14

import database.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_servicemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemetadata',
            name='provider',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=database.models.ServiceMetaData.default_array_field, size=None),
        ),
    ]
