# Generated by Django 2.1.7 on 2019-04-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20190425_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemetadata',
            name='db_name_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicemetadata',
            name='db_name_2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
