# Generated by Django 2.1.7 on 2019-04-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190425_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemetadata',
            name='db_name_0',
            field=models.CharField(default='', max_length=50),
        ),
    ]
