# Generated by Django 2.1.7 on 2019-04-26 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_pendingupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingupdates',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
