# Generated by Django 2.1.7 on 2019-04-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_pendingupdates_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingupdates',
            name='db_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
