# Generated by Django 2.1.7 on 2019-04-26 21:59

import database.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_pendingupdates_db_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingupdates',
            name='data',
        ),
        migrations.AddField(
            model_name='pendingupdates',
            name='data_date_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=database.models.PendingUpdates.default_string_array, size=None),
        ),
        migrations.AddField(
            model_name='pendingupdates',
            name='data_date_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=database.models.PendingUpdates.default_string_array, size=None),
        ),
        migrations.AddField(
            model_name='pendingupdates',
            name='data_string_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=database.models.PendingUpdates.default_string_array, size=None),
        ),
        migrations.AddField(
            model_name='pendingupdates',
            name='data_string_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=database.models.PendingUpdates.default_string_array, size=None),
        ),
        migrations.AddField(
            model_name='pendingupdates',
            name='data_time_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=database.models.PendingUpdates.default_string_array, size=None),
        ),
        migrations.AddField(
            model_name='pendingupdates',
            name='data_time_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), default=database.models.PendingUpdates.default_string_array, size=None),
        ),
    ]
