# Generated by Django 2.1.7 on 2019-04-26 22:26

import database.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20190426_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingupdates',
            name='data_string_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), default=database.models.PendingUpdates.default_string_array, size=None),
        ),
    ]
