# Generated by Django 2.1.7 on 2019-04-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20190426_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemetadata',
            name='updated_0',
        ),
        migrations.RemoveField(
            model_name='servicemetadata',
            name='updated_1',
        ),
        migrations.RemoveField(
            model_name='servicemetadata',
            name='updated_2',
        ),
    ]
