# Generated by Django 2.1.7 on 2019-04-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20190426_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='db_name_0',
            field=models.CharField(default='', max_length=50),
        ),
    ]
