# Generated by Django 2.1.7 on 2019-04-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_usermetadata_db_name_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmetadata',
            name='db_name_0',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingmetadata',
            name='db_name_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingmetadata',
            name='db_name_2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
