# Generated by Django 2.1.7 on 2019-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('U', 'Standard User'), ('A', 'Admin'), ('S', 'Service Provider')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
