# Generated by Django 2.1.7 on 2019-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190311_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
