# Generated by Django 2.1.7 on 2019-03-17 19:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusService',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('route', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('timing', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('price', models.IntegerField()),
                ('bus_number', models.CharField(max_length=20)),
                ('is_ready', models.BooleanField(default=False)),
            ],
        ),
    ]
