# Generated by Django 2.1.7 on 2019-03-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_busservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busservice',
            name='provider',
        ),
    ]
