# Generated by Django 2.1.7 on 2019-03-18 14:10

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_busservice_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busservice',
            name='bus_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='busservice',
            name='route',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=api.models.BusService.default_array_field, size=None),
        ),
        migrations.AlterField(
            model_name='busservice',
            name='timing',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=api.models.BusService.default_array_field, size=None),
        ),
    ]
