# Generated by Django 2.1.7 on 2019-03-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_busservice_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='busservice',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
