# Generated by Django 2.1.7 on 2019-03-20 19:06

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_busservice_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('check_in', models.CharField(blank=True, max_length=10)),
                ('check_out', models.CharField(blank=True, max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('provider', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=api.models.HotelService.default_array_field, size=None)),
                ('rooms', models.IntegerField(default=0)),
            ],
        ),
    ]
