# Generated by Django 2.1.7 on 2019-03-21 21:26

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_hotelservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelservice',
            name='location',
        ),
        migrations.AddField(
            model_name='busservice',
            name='boarding_point',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=api.models.BusService.default_array_field, size=None),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
