# Generated by Django 2.1.7 on 2019-04-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190321_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
