# Generated by Django 2.1.7 on 2019-04-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_hotelservice_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='check_in',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='check_out',
            field=models.TimeField(blank=True),
        ),
    ]
