# Generated by Django 2.1.7 on 2019-04-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190407_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
