# Generated by Django 2.1.7 on 2019-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190407_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
    ]
