# Generated by Django 2.1.7 on 2019-04-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190408_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='service',
            new_name='service_id',
        ),
    ]
