# Generated by Django 2.1.7 on 2019-04-09 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190408_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_date',
            field=models.DateField(default=datetime.date(2019, 4, 9)),
        ),
    ]
