# Generated by Django 2.1.7 on 2019-04-09 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_hotelbooking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
