# Generated by Django 2.1.7 on 2019-04-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190411_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
    ]
