# Generated by Django 2.1.7 on 2019-04-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_hotelbooking_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='bill',
            field=models.IntegerField(default=0),
        ),
    ]
