# Generated by Django 2.1.7 on 2019-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_hotelservice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
